[package]
name = "compiler-dodecahedron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = {version =  "170.1", features = ["prefer-dynamic"]}
